/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CoreApplication.Basket;

/**
 *
 * @author Richard North a0313108
 */
public class ROFCWindow1 extends javax.swing.JFrame {

    private Basket basket;
    /**
     * Creates new form ROFCWindow1
     */
    public ROFCWindow1() {
        initComponents();
        initListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        logoPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        leftButtonPanel = new GUI.LeftButtonPanel();
        bottomButtonPanel = new GUI.BottomButtonPanel();
        centrePanel = new GUI.CentrePanel();
        totalsPanel = new GUI.TotalsPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ROFC");
        setBackground(new java.awt.Color(0, 0, 0));
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        logoPanel.setBackground(new java.awt.Color(53, 127, 198));
        logoPanel.setFocusTraversalPolicyProvider(true);
        logoPanel.setPreferredSize(new java.awt.Dimension(428, 50));
        logoPanel.setLayout(new java.awt.GridBagLayout());

        logoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(0, 0, 0));
        logoLabel.setText("Real Office Furniture Company");
        logoLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 191, 6, 74);
        logoPanel.add(logoLabel, gridBagConstraints);

        getContentPane().add(logoPanel, java.awt.BorderLayout.NORTH);
        getContentPane().add(leftButtonPanel, java.awt.BorderLayout.LINE_START);
        getContentPane().add(bottomButtonPanel, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(centrePanel, java.awt.BorderLayout.CENTER);
        getContentPane().add(totalsPanel, java.awt.BorderLayout.LINE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ROFCWindow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ROFCWindow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ROFCWindow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ROFCWindow1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ROFCWindow1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BottomButtonPanel bottomButtonPanel;
    private GUI.CentrePanel centrePanel;
    private GUI.LeftButtonPanel leftButtonPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private GUI.TotalsPanel totalsPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * This method is used to initialise observers of this panel.
     */
    private void initListeners() {
        leftButtonPanel.addPanelObserver(centrePanel);
        bottomButtonPanel.addPanelObserver(centrePanel); 
        centrePanel.addPanelObserver(totalsPanel);
    }
    
}
