/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Interfaces.FormObserver;
import CoreApplication.BaseType;
import CoreApplication.Furniture;
import CoreApplication.Table;
import CoreApplication.WoodType;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Richard North a0313108
 */
public class TableForm extends javax.swing.JPanel {
    private List<FormObserver> observers = new ArrayList<>();
    private Table table;

    /**
     * Creates new form ChairForm
     */
    public TableForm() {
        initComponents();
        clearFill();
    }

    /**
     * Adds a observer to the collection to be notified
     * @param observer
     */ 
    public void addObserver(FormObserver observer) {
        observers.add(observer);
    }
    
    /**
     * calls the update method within all observers
     */
    public void updateObservers(Furniture item) {
        for (FormObserver observer : observers) {
            observer.updateBasket(item);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableImageLabel = new javax.swing.JLabel( new ImageIcon("images/table.jpg"));
        idNumberLabel = new javax.swing.JLabel();
        typeOfWoodLabel = new javax.swing.JLabel();
        baseTypeLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        tableDiameterLabel = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        idNumberTextField = new javax.swing.JTextField();
        tableDiameterTextField = new javax.swing.JTextField();
        typeOfWoodCombo = new javax.swing.JComboBox<>();
        baseTypeCombo = new javax.swing.JComboBox<>();
        addItemButton = new javax.swing.JButton();
        itemDescription = new javax.swing.JLabel();
        itemType = new javax.swing.JLabel();

        setBackground(new java.awt.Color(155, 217, 215));

        idNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        idNumberLabel.setText("ID Number");

        typeOfWoodLabel.setForeground(new java.awt.Color(0, 0, 0));
        typeOfWoodLabel.setText("Type of wood");

        baseTypeLabel.setForeground(new java.awt.Color(0, 0, 0));
        baseTypeLabel.setText("Type of base");

        quantityLabel.setForeground(new java.awt.Color(0, 0, 0));
        quantityLabel.setText("Quantity");

        tableDiameterLabel.setForeground(new java.awt.Color(0, 0, 0));
        tableDiameterLabel.setText("Table diameter");

        quantityTextField.setBackground(new java.awt.Color(255, 255, 255));
        quantityTextField.setForeground(new java.awt.Color(0, 0, 0));
        quantityTextField.setToolTipText("Enter the quantity needed");

        idNumberTextField.setBackground(new java.awt.Color(255, 255, 255));
        idNumberTextField.setForeground(new java.awt.Color(0, 0, 0));
        idNumberTextField.setToolTipText("Enter the item's ID number");

        tableDiameterTextField.setBackground(new java.awt.Color(255, 255, 255));
        tableDiameterTextField.setForeground(new java.awt.Color(0, 0, 0));
        tableDiameterTextField.setToolTipText("Enter the required table diameter in CM");

        typeOfWoodCombo.setBackground(new java.awt.Color(255, 255, 255));
        typeOfWoodCombo.setForeground(new java.awt.Color(0, 0, 0));
        typeOfWoodCombo.setModel(new DefaultComboBoxModel<>(WoodType.values()));
        typeOfWoodCombo.setToolTipText("Select the type of wood required");

        baseTypeCombo.setBackground(new java.awt.Color(255, 255, 255));
        baseTypeCombo.setForeground(new java.awt.Color(0, 0, 0));
        baseTypeCombo.setModel(new DefaultComboBoxModel<>(BaseType.values()));
        baseTypeCombo.setToolTipText("Select the  type of table base required");
        baseTypeCombo.setMinimumSize(new java.awt.Dimension(100, 22));
        baseTypeCombo.setPreferredSize(new java.awt.Dimension(100, 22));

        addItemButton.setBackground(new java.awt.Color(53, 127, 198));
        addItemButton.setForeground(new java.awt.Color(0, 0, 0));
        addItemButton.setText("Add item");
        addItemButton.setToolTipText("Click to add item to the basket");
        addItemButton.setMaximumSize(new java.awt.Dimension(80, 25));
        addItemButton.setMinimumSize(new java.awt.Dimension(80, 25));
        addItemButton.setPreferredSize(new java.awt.Dimension(80, 25));
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        itemDescription.setForeground(new java.awt.Color(0, 0, 0));
        itemDescription.setText("<html>This modern and practical table comes with <br>customisable options including oak or walnut wood <br>as well as the option to have a <br>chrome or wooden base. </html>");

        itemType.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        itemType.setForeground(new java.awt.Color(0, 0, 0));
        itemType.setText("Table");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tableImageLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(baseTypeLabel)
                            .addComponent(typeOfWoodLabel)
                            .addComponent(idNumberLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(baseTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(idNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(typeOfWoodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tableDiameterLabel)
                                        .addComponent(quantityLabel))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tableDiameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemType, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itemType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idNumberLabel)
                            .addComponent(tableDiameterLabel)
                            .addComponent(tableDiameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tableImageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeOfWoodLabel)
                    .addComponent(typeOfWoodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baseTypeLabel)
                    .addComponent(baseTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        try{
            if (Integer.parseInt(tableDiameterTextField.getText())>= 50){
                if(this.table != null){
                    this.table.setBaseType((BaseType)this.baseTypeCombo.getSelectedItem());
                    this.table.setTypeOfWood((WoodType)this.typeOfWoodCombo.getSelectedItem());
                    this.table.setDiameter(Integer.parseInt(tableDiameterTextField.getText()));
                    this.table.setIdNumber(Integer.parseInt(idNumberTextField.getText()));
                    this.table.setQuantity(Integer.parseInt(quantityTextField.getText()));
                    this.table.setItemPrice(this.table.calculatePrice());
                }else{
                    this.updateObservers(new Table(
                        Integer.parseInt(tableDiameterTextField.getText()),
                        (BaseType)baseTypeCombo.getSelectedItem(),
                        Integer.parseInt(idNumberTextField.getText()),
                        (WoodType)typeOfWoodCombo.getSelectedItem(), 
                        Integer.parseInt(quantityTextField.getText())));
                }
                clearFill();
            }else{
                JOptionPane.showMessageDialog(this,"<html>The table diameter is to small<br>"
                        + "Please enter a diameter greater than 50 </html>",
                        "Warning",JOptionPane.WARNING_MESSAGE);
            }
        }catch(Exception e){        
            JOptionPane.showMessageDialog(this,"Fields incorrectly filled",
                    "Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addItemButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemButton;
    private javax.swing.JComboBox<BaseType> baseTypeCombo;
    private javax.swing.JLabel baseTypeLabel;
    private javax.swing.JLabel idNumberLabel;
    private javax.swing.JTextField idNumberTextField;
    private javax.swing.JLabel itemDescription;
    private javax.swing.JLabel itemType;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JLabel tableDiameterLabel;
    private javax.swing.JTextField tableDiameterTextField;
    private javax.swing.JLabel tableImageLabel;
    private javax.swing.JComboBox<WoodType> typeOfWoodCombo;
    private javax.swing.JLabel typeOfWoodLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * This method is used to clear all data from the input fields.
     */
    public void clearFill(){
        this.table = null;
        this.baseTypeCombo.setSelectedItem(null);
        this.typeOfWoodCombo.setSelectedItem(null);
        this.idNumberTextField.setText(null);
        this.quantityTextField.setText(null);
        this.tableDiameterTextField.setText(null);
        this.addItemButton.setText("Add item");
    }
    
    /**
     * This method is used to prefill the input fields based of a chair item
     * @param item 
     */
    void setFill(Table item) {
        this.table = item;
        this.idNumberTextField.setText(String.valueOf(item.getIdNumber()));
        this.quantityTextField.setText(String.valueOf(item.getQuantity()));
        this.tableDiameterTextField.setText(String.valueOf(item.getDiameter()));
        this.baseTypeCombo.setSelectedItem(item.getBaseType());
        this.typeOfWoodCombo.setSelectedItem(item.getTypeOfWood());
        this.addItemButton.setText("Edit item");
    }
}
