/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Interfaces.CentrePanelObserver;


/**
 *
 * @author Richard North a0313108
 */
public class TotalsPanel extends javax.swing.JPanel implements CentrePanelObserver{

    /**
     * Creates new form TotalsPanel1
     */
    public TotalsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemsPriceLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(200, 300));
        setPreferredSize(new java.awt.Dimension(200, 300));
        setLayout(new java.awt.BorderLayout());

        itemsPriceLabel.setBackground(new java.awt.Color(204, 204, 255));
        itemsPriceLabel.setForeground(new java.awt.Color(0, 0, 0));
        itemsPriceLabel.setToolTipText("");
        add(itemsPriceLabel, java.awt.BorderLayout.CENTER);
        add(totalLabel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel itemsPriceLabel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void CentrePanelUpdateItems(String text) {
        itemsPriceLabel.setText(text);
        
    }

    @Override
    public void CentrePanelUpdateTotal(String text) {
        totalLabel.setText("Total: "+text);
        
    }

    @Override
    public void centrePanelClear() {
        itemsPriceLabel.setText("");
        totalLabel.setText("");
    }
}
